### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by abdurrahmanekr** [abdurrahmanekr/kodabug#3]
- [x] Global menüde kullanıcının ismi, puanı, rütbesi yazılması (görev kartı şu an önemli değil)
- [x] Global menüye ayarlar ikonu eklenip ayarlar sayfasının yapılması
- [x] Soru gönderme ekranı, register ekranı geriye gelmek için navbar button koyulması
- [x] Kullanıcı register olduktan sonra session_ticket'ın kaydedilmesi
- [x] GetUserVCard çekilmesine rağmen başlık ikonlarındaki sayılar gelmiyor
- [x] SendGame sayfasının tasarımı, GameQuestionMain sayfasının gibi olması gerekiyor

**Not:** Bu issue üzerindeki bir işi aldıysanız veya bitirdiyseniz, bu issue altına commit'in idsini comment atmanız yeterli.
