### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by abdurrahmanekr** [abdurrahmanekr/kodabug#4]
- [x] Configde bulunan field ayarlamaları daha anlaşılır bir şekilde getirilmesi gerekiyor. ör: RegisterService.uploadGame(.......) yerine RegisterService.uploadGame({...}) şeklinde object olarak dönüş yapılması gerekiyor, İleride bir field ekleneceği veya çıkarılacağı zaman servislerde bulunan tüm parametreleri değiştirmek zorunda kalmaktan kurtulmuş oluruz.
- [x] Ayarlar sayfasında profil bilgilerini değiştirebileceği yer eklenmesi
- [x] Ayarlar sayfasında güvenlik bilgilerini değiştirebileceği yer eklenmesi
- [x] Mail (usmail) ve birth değerleri. eklenecek
- [x] Geri butonu deprecated işleminin tamamlanması
**Not:** Bu issue üzerindeki bir işi aldıysanız veya bitirdiyseniz, 
commit'e **see #4** şeklinde yazmanız yeterli.
