### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by abdurrahmanekr** [abdurrahmanekr/kodabug#6]
- [x] Profil fotoğrafının çerezlerden gelmesi engellenecek
- [x] Profili düzenle ekranında kullanıcı fotoğrafını güncelleyebilecek
- [x] Profil ayarları yapıldıktan sonra user değeri GLOBALS.user'a güncellenecek
- [x] Oynamak için tıkla ekranı çalışır hale getirilecek
- [x] GameQuestionMain sayfasında loading ve süre eklenecek
- [x] ios'da bulunan tasarım sorunları giderilecek

 Bu issue üzerindeki bir işi aldıysanız veya bitirdiyseniz,
commit'e **see #6**  şeklinde yazmanız yeterli.
