### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by abdurrahmanekr** [abdurrahmanekr/kodabug#7]
Şu ana kadar yaptığımız çoğu önemli sıkıntı giderildi. @kipcakbegi öncelikle seni sonra beni tebrik ediyorum.
#  😄 💯 👍 🥇 🎉 
Artık kullanıcının oyun oynaması gerekiyor.
- [x] startGame ile bir oyunun başlatılması gerekiyor // edit
- [x] Kullanıcı oynamaya tıkladığı zaman ilk önce [getRandomGame](http://api.kodabug.net/docs/?service=GameService&method=getRandomGame) methodunu çağırması gerekiyor
- [x] Ardından [getGame](http://api.kodabug.net/docs/?service=GameService&method=getGame) methodunu çağırarak oynaması gereken soruyu getirecek
- [x] Gelen soru kullanıcıya sunulacak ve cevapladığı anda [getTrueOption](http://api.kodabug.net/docs/?service=GameService&method=getTrueOption) çalışacak ve sunucudan o sorunun doğru şıkkı gelecek
- [x] Gelen doğru şık ile kullanıcının cevabı karşılaştırılacak ve kullanıcı bilgilendirilecek
