### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by abdurrahmanekr** [abdurrahmanekr/kodabug#8]
Kullanıcı oyun oynayabiliyor ❤️ Oyunu kazanan veya kaybeden kullanıcı için işlemler gerekli.
- [x] Oyunu bitiren kullanıcı win sayfasına veya lose sayfasına yönlendirilecek
- [x] Win sayfasında devam'a tıklayan kullanıcı aynı şeklide tekrar GameQuestionMain sayfasına yönlendirilecek
- [x] Lose sayfasından çıkan kullanıcı Main'e yönlendirilecek
- [x] Main'de bulunan gameList oyun bitince güncellenecek

Bunun yanında kullanıcı zaman aşımında yapılması gerekenler
- [x] Kullanıcıya verilen süre bittiğinde kaybedecek
- [x] Çağırdığı getTrueOption methodu eğer `-1` döndürürse yine kaybetti olarak işaretlenecek

### 🏷

> see #8
